# Pokemon

### Introduction:

This time you will create the data.



### Step 1. Import the necessary libraries

In [1]:
import pandas as pd
import numpy as np

### Step 2. Create a data dictionary that looks like the DataFrame below

In [2]:
raw_data = {"name": ['Bulbasaur', 'Charmander','Squirtle','Caterpie'],
            "evolution": ['Ivysaur','Charmeleon','Wartortle','Metapod'],
            "type": ['grass', 'fire', 'water', 'bug'],
            "hp": [45, 39, 44, 45],
            "pokedex": ['yes', 'no','yes','no']
            }

### Step 3. Assign it to a variable called pokemon

In [3]:
pokemon = pd.DataFrame(raw_data)
pokemon.head()

         name   evolution   type  hp pokedex
0   Bulbasaur     Ivysaur  grass  45     yes
1  Charmander  Charmeleon   fire  39      no
2    Squirtle   Wartortle  water  44     yes
3    Caterpie     Metapod    bug  45      no

### Step 4. Ops...it seems the DataFrame columns are in alphabetical order. Place  the order of the columns as name, type, hp, evolution, pokedex

In [4]:
pokemon = pokemon[['name', 'type', 'hp', 'evolution','pokedex']]
pokemon

         name   type  hp   evolution pokedex
0   Bulbasaur  grass  45     Ivysaur     yes
1  Charmander   fire  39  Charmeleon      no
2    Squirtle  water  44   Wartortle     yes
3    Caterpie    bug  45     Metapod      no

### Step 5. Add another column called place, and insert what you have in mind.

In [5]:
places = ['Kanto', 'Johto', 'Hoenn', 'Sinnoh']
pokemon['places'] = places
pokemon

         name   type  hp   evolution pokedex  places
0   Bulbasaur  grass  45     Ivysaur     yes   Kanto
1  Charmander   fire  39  Charmeleon      no   Johto
2    Squirtle  water  44   Wartortle     yes   Hoenn
3    Caterpie    bug  45     Metapod      no  Sinnoh

### Step 6. Present the type of each column

In [6]:
pokemon.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   name       4 non-null      object
 1   type       4 non-null      object
 2   hp         4 non-null      int64
 3   evolution  4 non-null      object
 4   pokedex    4 non-null      object
 5   places     4 non-null      object
dtypes: int64(1), object(5)
memory usage: 324.0+ bytes

### BONUS: Create your own question and answer it.

In [7]:
#Am I getting better? Yes